### ISSUE TITLE
ETL job errors if there are no videos to process and parallel processing is requested

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/aind-behavior-video-transformation#19]
I would expect this to create the output directory and exit instead of erroring.

```
$ python -m aind_behavior_video_transformation.etl -j '{"input_source": "foo", "output_directory": "bar",  "compression_requested": {"compresison_enum": "gamma fix colorspace"}}'
<frozen runpy>:128: RuntimeWarning: 'aind_behavior_video_transformation.etl' found in sys.modules after import of package 'aind_behavior_video_transformation', but prior to execution of 'aind_behavior_video_transformation.etl'; this may result in unpredictable behaviour
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/galen.lynch/Documents/Code/aind-behavior-video-transformation/src/aind_behavior_video_transformation/etl.py", line 183, in <module>
    job_response = job.run_job()
  File "/home/galen.lynch/Documents/Code/aind-behavior-video-transformation/src/aind_behavior_video_transformation/etl.py", line 153, in run_job
    self._run_compression(convert_video_args)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/galen.lynch/Documents/Code/aind-behavior-video-transformation/src/aind_behavior_video_transformation/etl.py", line 87, in _run_compression
    with ProcessPoolExecutor(max_workers=num_jobs) as executor:
         ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/concurrent/futures/process.py", line 666, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
```
https://github.com/AllenNeuralDynamics/aind-behavior-video-transformation/blob/153d898dc500308f6a43b179bdfc9302f48e24c0/src/aind_behavior_video_transformation/etl.py#L87

**Comment by galenlynch** [comment]
Closed by #20
